### ISSUE TITLE
Get the NASA API Key

### ISSUE THREAD

**Issue by montel26** [montel26/NASA-APP#5]
File: get_api_key.py
Task:
You need to create a function that retrieves and stores the NASA API key.

Function Name: get_api_key()
Description: This function should return the NASA API key. Initially, use 'DEMO_KEY' as the placeholder key. Once you have an actual key, replace it.
Key Learning Point: Understand how API keys work, why they are needed, and how to use them.

**Comment by tcpilane** [comment]
Guys here are a few resources to help you out with getting started:
https://www.dataquest.io/blog/python-api-tutorial/
https://requests.readthedocs.io/en/latest/
